# Generated by Django 4.1.5 on 2023-02-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='valordecompra',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
